name: Reverse Engineering Analysis

on:
  workflow_dispatch:

jobs:
  analyze:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download Netease Launcher
      run: curl -L "https://adl.netease.com/d/g/bloodstrike/c/pc" -o NeteaseLauncher.exe

    - name: Download and Extract Sysinternals
      run: |
        curl -L "https://download.sysinternals.com/files/SysinternalsSuite.zip" -o Sysinternals.zip
        Expand-Archive -Path Sysinternals.zip -DestinationPath .
      shell: pwsh

    - name: Run strings.exe on the launcher
      run: |
        ./strings.exe -accepteula -a -n 8 NeteaseLauncher.exe > launcher_strings.txt
      shell: pwsh

    - name: Upload analysis result
      uses: actions/upload-artifact@v4
      with:
        name: launcher-analysis-result
        path: launcher_strings.txt
