name: Reverse Engineering Analysis

on:
  workflow_dispatch:

jobs:
  analyze:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download Full Game Executable
      run: curl -L "https://g83naxx1ena.gdl.easebar.com/bloodstrike_global_1.003.750005.1779761549.exe" -o BloodStrike_full.exe

    - name: Download and Extract Sysinternals
      run: |
        curl -L "https://download.sysinternals.com/files/SysinternalsSuite.zip" -o Sysinternals.zip
        Expand-Archive -Path Sysinternals.zip -DestinationPath .
      shell: pwsh

    - name: Run strings.exe on the full executable
      run: |
        ./strings.exe -accepteula -a -n 8 BloodStrike_full.exe > full_game_strings.txt
      shell: pwsh

    - name: Upload analysis result
      uses: actions/upload-artifact@v4
      with:
        name: full-game-analysis-result
        path: full_game_strings.txt
